TOP=ps2_cursor
SRCS= src/$(TOP).vhdl ../common/pll.vhdl ../common/vga.vhdl ../common/ps2.vhdl ../common/uart.vhdl
CCF=../common/evb-vga.ccf ../common/evb-ps2.ccf ../common/evb-uart.ccf

include ../common/common.make
